### ISSUE TITLE
Configuration breaks bed leveling routine from printer UI

### ISSUE THREAD

**Issue by carlosg-gh** [qidi-community/config-xplus4#1]
![image](https://github.com/user-attachments/assets/5c6e9eee-976e-4a1d-ae68-0041c7010468)

Seems like the `CLEAR_NOZZLE` macro is conflicting with the internal routine for the bed leveling assistant. It will indefinetly wait for the nozzle to be cooled down before proceeding, but the temperature is set to 170C and it won't change, locking the printer in this state.

**Comment by vega-d** [comment]
this was solved in https://github.com/qidi-community/config-xplus4/commit/bc6fb5173f3e0728205cf8b0db48f96ebdd92501
