### ISSUE TITLE
[Feature Request] Do not home Z axis on load / unload filament command.

### ISSUE THREAD

**Issue by jumika** [qidi-community/config-xplus4#3]
Homing the Z axis when loading (`M604`) / unloading (`M603`) filament can be dangerous when you try to do it right after a print. If you did not remove the print from the bed it can (and probably will) crash the printhead into the print. As I see it is completely unnecessary to home the Z axis in this case, because moves happen on the X and Y axes only.
Looking at the `gcode_macro.cfg` file I've found calls to the `_CG28` macro which in my understanding homes all the axes if any of them are not homed.
I suggest changing the load and unload filament macros not to use `_CG28` but instead a similar macro that does the same but only on X and Y axes. The reason for not changing the `_CG28` itself is it could be used internally elsewhere which we are not aware of so I prefer not to touch it.
I'd like to ask some of you who are more experienced to check my proposed approach and give their blessing, or even better implement the changes. I'd like to implement it myself, but I have really limited knowledge in reading and writing GCODE.

**Comment by vega-d** [comment]
This was addressed in https://github.com/qidi-community/config-xplus4/commit/3288fa47454f4be3586c92b1b2c186ffccaf5b4a, it now only homes XY axis, and only if needed.
